extends:
  - airbnb-base
rules:
  array-bracket-spacing:
    - error
    - always
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: false
  comma-dangle:
    - error
    - never
  eol-last:
    - error
    - always
  func-names:
    - error
    - never
  no-multiple-empty-lines:
    - error
    - max: 2
      maxBOF: 0
      maxEOF: 1
  no-param-reassign:
    - error
    - props: false
  no-console: off
  quotes:
    - error
    - double
  semi:
    - error
    - always